CREATE TABLE IF NOT EXISTS ADM_PROGRAM_STG
(
    JOB_ID               VARCHAR(50) NOT NULL,
    PROGRAM_CODE         VARCHAR(30) NOT NULL,
    PROGRAM_NAME         VARCHAR(200) NOT NULL,
    START_DATE           DATE NULL,
    END_DATE             DATE NULL,
    CAPACITY             NUMERIC(10) NULL,
    USE_YN               CHAR(1) NOT NULL DEFAULT 'Y',
    DESCRIPTION          VARCHAR(1000) NULL,
    REG_ID               VARCHAR(20) NULL,
    REG_DT               DATETIME NULL,
    UPD_ID               VARCHAR(20) NULL,
    UPD_DT               DATETIME NULL,
    KEY ADM_PROGRAM_STG_IDX1 (JOB_ID)
);

CREATE TABLE IF NOT EXISTS ADM_UPLOAD_JOB
(
    JOB_ID               VARCHAR(50) NOT NULL,
    FILE_NAME            VARCHAR(255) NOT NULL,
    FILE_TYPE            VARCHAR(10) NOT NULL,
    STATUS               VARCHAR(20) NOT NULL,
    TOTAL_COUNT          INT NOT NULL DEFAULT 0,
    SUCCESS_COUNT        INT NOT NULL DEFAULT 0,
    ERROR_COUNT          INT NOT NULL DEFAULT 0,
    MESSAGE              VARCHAR(1000) NULL,
    START_DT             DATETIME NULL,
    END_DT               DATETIME NULL,
    REG_ID               VARCHAR(20) NULL,
    REG_DT               DATETIME NOT NULL,
    PRIMARY KEY (JOB_ID)
);

CREATE TABLE IF NOT EXISTS ADM_UPLOAD_ERROR
(
    JOB_ID               VARCHAR(50) NOT NULL,
    ROW_NO               INT NOT NULL,
    FIELD_NAME           VARCHAR(50) NULL,
    ERROR_MESSAGE        VARCHAR(1000) NOT NULL,
    RAW_DATA             VARCHAR(2000) NULL,
    REG_DT               DATETIME NOT NULL,
    KEY ADM_UPLOAD_ERROR_IDX1 (JOB_ID),
    KEY ADM_UPLOAD_ERROR_IDX2 (ROW_NO)
);
